import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'pages/language_selection.dart';
// Use the updated home page that includes new features like video and PDF.
import 'pages/home_page_updated.dart';
import 'firebase_options.dart';

/// Entry point of the application. It ensures that Firebase and
/// local persistence (SharedPreferences) are initialised before the
/// widget tree is built. Based on whether a language has been selected
/// previously, the app navigates to the language selection screen or
/// directly to the home screen.
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialise Firebase. The options are generated by the FlutterFire CLI.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Access shared preferences to determine if the user has already selected a language.
  final prefs = await SharedPreferences.getInstance();
  final selectedLang = prefs.getString('selected_language');
  runApp(MyApp(isFirstRun: selectedLang == null));
}

/// Root widget for the admin application.
class MyApp extends StatelessWidget {
  final bool isFirstRun;

  const MyApp({super.key, required this.isFirstRun});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Admin Panel',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.deepPurple,
        useMaterial3: true,
      ),
      home: isFirstRun
          ? const LanguageSelectionPage()
          : const HomePageUpdated(),
    );
  }
}